coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        paths:
          - "packages/dilithium5/coverage.lcov"
        # advanced
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
        flags:
          - dilithium5
    patch:
      default:
        target: 0%